### ISSUE TITLE
Update create account form

### ISSUE THREAD

**Issue by PeterArbaugh** [onflow/faucet#5]
as a user, I can create a Flow Testnet account

**Notes:**

Scope for this ticket is to update the account creation form - other page elements will be handled separately.

Should contain:
- Public key
    - Label
    - Description (copy tbd)
    - Input field
- Signature & hash algorithm
    - Label
    - Description (copy tbd)
    - Signature algorithm select. Options:
        - ECDSA_P256 (default)
        - ECDSA_secp256k1
    - Hash algorithm select. Options:
        - SHA2_256 (default)
        - SHA3_256
- hCaptcha
- Create new account button

**Design:**
[Figma](https://www.figma.com/file/XzFmInawRB4dilexjDpxPm/Dapper-Flow-Designs?node-id=33%3A403)

**Comment by kerrywei** [comment]
confirmed this is no longer relevant, close it for now
