### ISSUE TITLE
Make Faucet Smart (send test Flow to the correct account EVM/Cadence)

### ISSUE THREAD

**Issue by gregsantos** [onflow/faucet#69]
[Flow Faucet EVM PRD](https://docs.google.com/document/d/1SIaw0tndOHgImgJUgLz4FvlPIV7WaBKKIPr4q_31-pY/edit#heading=h.1prslla8249b)

```[tasklist]
### Tasks
- [ ] https://github.com/onflow/faucet/issues/94
```

**Comment by gregsantos** [comment]
Looks like this is not blocked by VM Bridge. 
@sisyphusSmiling will work on the transaction to fund COA and transfer to EOA.
I guess same tx will need to check for existing COA and create if non-existent 🤔or will we need to create corresponding COA first from CLI? @JeffreyDoyle 
Some additional UI changes were added to the linked PRD.

**Comment by sisyphusSmiling** [comment]
FYI this is WIP on [enable-evm branch](https://github.com/onflow/faucet/tree/enable-evm)
