### ISSUE TITLE
use keys.add to create account instead of addPublicKey

### ISSUE THREAD

**Issue by rrrkren** [onflow/faucet#95]
### Issue To Be Solved

`addPublicKey` has been deprecated and will be removed in stable cadence. We should use `keys.add` instead. The events emitted for these two calls are actually different.

### Suggested Solution

use `account.keys.add` instead of `account.addPublicKey` here 
https://github.com/onflow/faucet/blob/main/lib/flow/account.ts#L20
the params will need to be explicitly passed in as opposed to encoded in the arg as byte array.

**Comment by gregsantos** [comment]
Done and will be merged soon
